NUMBERS = tuple(
    '%s\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}' % i
    for i in range(10)
) + ('\N{KEYCAP TEN}',)
LETTERS = tuple(
    chr(ord('\N{REGIONAL INDICATOR SYMBOL LETTER A}') + i)
    for i in range(26)
)

PLUS = '\N{HEAVY PLUS SIGN}'
CHECK = '\N{WHITE HEAVY CHECK MARK}'
CROSS = '\N{NEGATIVE SQUARED CROSS MARK}'
SHAKE = '\N{HANDSHAKE}'
MAG = '\N{LEFT-POINTING MAGNIFYING GLASS}'
CR0SS = '\N{CROSS MARK}'
QUESTION = '\N{BLACK QUESTION MARK ORNAMENT}'

SPADES = '<:spades:701646576153526353>'
CLUBS = '<:clubs:701646604347637801>'
HEARTS = '\N{BLACK HEART SUIT}'
DIAMONDS = '\N{BLACK DIAMOND SUIT}'

BLACK_SQUARE = '\N{BLACK LARGE SQUARE}'
WHITE_SQUARE = '\N{WHITE LARGE SQUARE}'
ZWSP = '\N{ZERO WIDTH SPACE}'

BLUE_CIRCLE = '\N{LARGE BLUE CIRCLE}'
RED_CIRCLE = '\N{LARGE RED CIRCLE}'

SEE_DM = '<:see_dm:729737107811074157>'
